#ifndef _OPENGL_BLUE_MARBLE_WINDOW_HH_INCLUDED_
#define _OPENGL_BLUE_MARBLE_WINDOW_HH_INCLUDED_

#define BM_INIT_WINDOW_WIDTH (800)
#define BM_INIT_WINDOW_HEIGHT (600)
#define BM_WINDOW_TITLE "Blue Marble"

#endif
